[package]
name = "meowpad_configurator"
version = "0.2.4"
description = "A Tauri App"
authors = ["fantasyzhjk", "monodesu"]
license = ""
repository = ""
default-run = "meowpad_configurator"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.0.0"
tauri = { version = "1.2.4", features = ["api-all"] }
hidapi-rusb = "1.3.2"
pretty-hex = "0.3.0"
once_cell = "1.17.1"
anyhow = "1.0.70"
log = "0.4.17"
env_logger = "0.10.0"
toml = "0.7.3"
notify = "4.0.17"
meowpad = { path = "./meowpad" }
reqwest = { version = "0.11", features = ["json"] }
regex = "1.7.1"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
