[package]
name = "meowpad_configurator"
version = "1.0.0"
description = "A Tauri App"
authors = ["fantasyzhjk", "monodesu"]
license = ""
repository = ""
default-run = "meowpad_configurator"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.4.0"
tauri = { version = "1.5.3", features = ["api-all"] }
hidapi-rusb = "1.3.3"
pretty-hex = "0.4.0"
once_cell = "1.18.0"
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.10.1"
toml = "0.8.8"
notify = "4.0.17"
meowpad = { path = "./meowpad" }
hid-iap = { path = "./hid-iap" }
reqwest = { version = "0.11", features = ["json"] }
regex = "1.10.2"
thiserror = "1.0.50"
better-panic = "0.3.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
