/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application.vue')['default']
    DeveloperSettings: typeof import('./src/components/DeveloperSettings.vue')['default']
    FirmwareUpdate: typeof import('./src/components/FirmwareUpdate.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Key: typeof import('./src/components/Key.vue')['default']
    Keyboard: typeof import('./src/components/Keyboard.vue')['default']
    KeyCalibrate: typeof import('./src/components/Keyboard/KeyCalibrate.vue')['default']
    KeyDebug: typeof import('./src/components/Keyboard/KeyDebug.vue')['default']
    KeyFrame: typeof import('./src/components/Keyboard/KeyFrame.vue')['default']
    KeyHall: typeof import('./src/components/Keyboard/KeyHall.vue')['default']
    KeyModal: typeof import('./src/components/KeyModal.vue')['default']
    KeyModify: typeof import('./src/components/Keyboard/KeyModify.vue')['default']
    KeyModifyOption: typeof import('./src/components/Keyboard/KeyModifyOption.vue')['default']
    KeySelect: typeof import('./src/components/Keyboard/KeySelect.vue')['default']
    KeyShow: typeof import('./src/components/KeyShow.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
  }
}
