/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application.vue')['default']
    ColorSetting: typeof import('./src/components/meowpad4k/ColorSetting.vue')['default']
    Debug: typeof import('./src/components/Debug.vue')['default']
    DeveloperSettings: typeof import('./src/components/DeveloperSettings.vue')['default']
    DeviceSetting: typeof import('./src/components/meowpad3k/DeviceSetting.vue')['default']
    FirmwareUpdate: typeof import('./src/components/FirmwareUpdate.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IAP: typeof import('./src/components/IAP.vue')['default']
    Key: typeof import('./src/components/Key.vue')['default']
    Keyboard: typeof import('./src/components/meowpad3k/Keyboard.vue')['default']
    KeyCalibrate: typeof import('./src/components/Keyboard/KeyCalibrate.vue')['default']
    KeyDebug: typeof import('./src/components/Keyboard/KeyDebug.vue')['default']
    KeyFrame: typeof import('./src/components/Keyboard/KeyFrame.vue')['default']
    KeyHall: typeof import('./src/components/Keyboard/KeyHall.vue')['default']
    KeyModal: typeof import('./src/components/KeyModal.vue')['default']
    KeySelect: typeof import('./src/components/Keyboard/KeySelect.vue')['default']
    KeyShow: typeof import('./src/components/KeyShow.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    Settings: typeof import('./src/components/meowpad3k/Settings.vue')['default']
  }
}
