/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application.vue')['default']
    ColorSetting: typeof import('./src/components/meowpadv2/ColorSetting.vue')['default']
    ConfigKb: typeof import('./src/components/pure64/ConfigKb.vue')['default']
    ConfigKeys: typeof import('./src/components/pure64/ConfigKeys.vue')['default']
    Debug: typeof import('./src/components/DeveloperSetting/Debug.vue')['default']
    DebugForV3: typeof import('./src/components/DeveloperSetting/DebugForV3.vue')['default']
    DeveloperSettings: typeof import('./src/components/DeveloperSetting/DeveloperSettings.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    DeviceSetting: typeof import('./src/components/meowpadv2/DeviceSetting.vue')['default']
    FirmwareUpdate: typeof import('./src/components/FirmwareUpdate.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IAP: typeof import('./src/components/DeveloperSetting/IAP.vue')['default']
    Key: typeof import('./src/components/KeyComponents/Key.vue')['default']
    Keyboard: typeof import('./src/components/meowpadv2/Keyboard.vue')['default']
    KeyboardMenu: typeof import('./src/components/pure64/KeyboardMenu.vue')['default']
    KeyCalibrate: typeof import('./src/components/pure64/Keyboard/KeyCalibrate.vue')['default']
    KeyDebug: typeof import('./src/components/KeyComponents/KeyDebug.vue')['default']
    KeyFrame: typeof import('./src/components/pure64/Keyboard/KeyFrame.vue')['default']
    KeyHall: typeof import('./src/components/pure64/Keyboard/KeyHall.vue')['default']
    KeyModal: typeof import('./src/components/KeyComponents/KeyModal.vue')['default']
    KeyModalSelect: typeof import('./src/components/KeyComponents/KeyModalSelect.vue')['default']
    KeyModalV2: typeof import('./src/components/KeyComponents/KeyModalV2.vue')['default']
    KeyModify: typeof import('./src/components/pure64/Keyboard/KeyModify.vue')['default']
    KeyModifyOption: typeof import('./src/components/pure64/Keyboard/KeyModifyOption.vue')['default']
    KeyShow: typeof import('./src/components/KeyComponents/KeyShow.vue')['default']
    KeySocd: typeof import('./src/components/pure64/Keyboard/KeySocd.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    ModifyKeys: typeof import('./src/components/pure64/ModifyKeys.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/meowpadv2/Settings.vue')['default']
    SocdBind: typeof import('./src/components/pure64/SocdBind.vue')['default']
  }
}
