[package]
name = "hid-iap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi-rusb = "1.3.3"
thiserror = "1.0.50"