/**
 * Type declarations for WASM module
 * The actual module is generated by wasm-pack at build time
 */

declare module '../../wasm/meowpad_wasm.js' {
  export default function init(): Promise<void>;
  
  export function init_logger(): void;
  export function is_webhid_available(): boolean;
  export function version(): string;
  export function enumerate_devices(): Promise<any>;
  export function request_device(vendor_id: number, product_id: number): Promise<number>;
  export function test_device(device_id: number): boolean;
  
  // Pure64 functions
  export function pure64_calibration_key(device_id: number, key_indexes: Uint8Array): void;
  export function pure64_check_raw_config(config: string): boolean;
  export function pure64_clear_config(device_id: number): void;
  export function pure64_erase_firmware(device_id: number): void;
  export function pure64_get_debug_value(device_id: number): Promise<any>;
  export function pure64_get_debug_value_part(device_id: number, index: number): Promise<any>;
  export function pure64_get_default_key_config(): any;
  export function pure64_get_device_info(device_id: number): any;
  export function pure64_get_device_status(device_id: number): any;
  export function pure64_get_firmware_version(): any;
  export function pure64_get_hall_config(device_id: number): Promise<any>;
  export function pure64_get_key_calibrate_status(device_id: number): Promise<any>;
  export function pure64_get_key_config(device_id: number): Promise<any>;
  export function pure64_get_keystates(device_id: number): Promise<any>;
  export function pure64_get_keyvalues(device_id: number): Promise<any>;
  export function pure64_get_raw_config(device_id: number): string;
  export function pure64_ping(device_id: number): boolean;
  export function pure64_probe_device(hid_device_js: any): any;
  export function pure64_reset_device(device_id: number): void;
  export function pure64_save_key_config(device_id: number): void;
  export function pure64_save_raw_config(device_id: number, config: string): void;
  export function pure64_set_key_config(device_id: number, config: any): void;
}
