[package]
name = "meowpad_wasm"
version = "1.2.1"
edition = "2021"
description = "WebHID implementation for Meowpad configurator"
authors = ["fantasyzhjk", "monodesu"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.69", features = [
    "Navigator",
    "Window",
    "Performance",
    "console",
    "HidInputReportEvent",
] }
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.4"
thiserror = "2"
log = "0.4"
wasm-logger = "0.2"
getrandom = { version = "0.4", features = ["wasm_js"] }
toml = "0.9"
async-trait = "0.1"

# Device libraries
meowpad = { path = "../src-tauri/meowpad" }
meowpadv3 = { path = "../src-tauri/meowpadv3" }
meowpad4k = { path = "../src-tauri/meowpadv2" }
meowpad3k = { path = "../src-tauri/meowpadv2se" }
meowpadv21se = { path = "../src-tauri/meowpadv21se" }
meowboard = { path = "../src-tauri/pure64" }

[profile.release]
# This makes the WASM binary much smaller
opt-level = "z"
lto = true
codegen-units = 1
