# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Build Artifacts
on:
  pull_request:
    paths:
      - '.github/workflows/build-artifacts.yml'
      - '**'

jobs:
  build-artifacs:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: nightly

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false


      - name: install libs (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libusb-1.0-0

      - name: install deps
        working-directory: ./
        run: |
          pnpm install --no-frozen-lockfile

      - name: build artifacts
        working-directory: ./
        run: |
          pnpm run tauri build

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: linux-deb
          path: ./src-tauri/target/release/bundle/deb/meowpad-configurator_*.deb

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: linux-appimage
          path: ./src-tauri/target/release/bundle/appimage/meowpad-configurator_*.AppImage

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'windows-latest'
        with:
          name: windows-exe
          path: ./src-tauri/target/release/MeowpadConfigurator.exe

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'windows-latest'
        with:
          name: windows-msi
          path: ./src-tauri/target/release/bundle/msi/*

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'macos-latest'
        with:
          name: macos-app
          path: ./src-tauri/target/release/bundle/macos/MeowpadConfigurator.app
